[package]
name = "bg3-modorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.20"
pak_reader = { path = "../pak_reader" }
quick-xml = "0.30.0"
