[package]
name = "pak_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.0"
flate2 = "1.0.27"
log = "0.4.20"
lz4_flex = "0.11.1"
nom = "*"
